sudo: required

language: go

services:
  - docker

go:
  - 1.7

install:
  - echo "no install!"

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - travis

script:
  - go test
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push USER/REPO;
